### PR TITLE
upgrade to calico v3.22.0

### PR DESCRIPTION
**Pull request by ericgraf**
Towards https://github.com/giantswarm/giantswarm/issues/19842

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Review by kopiczko — APPROVED** [review]
If it rolls without issues

**Review by marians — APPROVED** [review]
🤷

**Comment by tfussell** [comment]
Needs to be tested.

**Review by kubasobon — APPROVED** [review]

**Comment by glitchcrab** [comment]
closing this as we won't be doing it

**Pull request closed without merging**
